// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWlohLKI9sTQlABGoeA3EspvQThHEe98A',
    appId: '1:822002297591:web:5cd4b96c04a7f83b1d81f2',
    messagingSenderId: '822002297591',
    projectId: 'boardgameplayer-6f963',
    authDomain: 'boardgameplayer-6f963.firebaseapp.com',
    storageBucket: 'boardgameplayer-6f963.firebasestorage.app',
    measurementId: 'G-651ZMMVM6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqMiuvL155oxb9MzfZ-hTWg4Y1OjGB2I',
    appId: '1:822002297591:android:509c80ea85df11f11d81f2',
    messagingSenderId: '822002297591',
    projectId: 'boardgameplayer-6f963',
    storageBucket: 'boardgameplayer-6f963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDSVpEgocqGyNg24vtfoI5h9BNDX-m3g',
    appId: '1:822002297591:ios:86c668d5928284591d81f2',
    messagingSenderId: '822002297591',
    projectId: 'boardgameplayer-6f963',
    storageBucket: 'boardgameplayer-6f963.firebasestorage.app',
    iosBundleId: 'com.example.progettinoIos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMDSVpEgocqGyNg24vtfoI5h9BNDX-m3g',
    appId: '1:822002297591:ios:86c668d5928284591d81f2',
    messagingSenderId: '822002297591',
    projectId: 'boardgameplayer-6f963',
    storageBucket: 'boardgameplayer-6f963.firebasestorage.app',
    iosBundleId: 'com.example.progettinoIos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWlohLKI9sTQlABGoeA3EspvQThHEe98A',
    appId: '1:822002297591:web:8b6e4e79714a7e2b1d81f2',
    messagingSenderId: '822002297591',
    projectId: 'boardgameplayer-6f963',
    authDomain: 'boardgameplayer-6f963.firebaseapp.com',
    storageBucket: 'boardgameplayer-6f963.firebasestorage.app',
    measurementId: 'G-QHL41VPJRG',
  );
}
